version: '3.5'

services:
#  helppostgresql:
#    build: .
#    container_name: ajudaime-postgres
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
##      PGPASSFILE: '/.pgpass'
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./pgsql-data:/var/lib/postgresql/data
#    networks:
#      - ajudaime-net
#
#  helppgadmin4:
#    image: dpage/pgadmin4
#    container_name: ajudaime-pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
#    ports:
#      - 8090:80
#    links:
#      - helppostgresql
#    networks:
#      - ajudaime-net

  elasticsearch:
    image: elasticsearch:6.5.0
    container_name: ajudaime-elasticsearch
    ports:
      - "9200:9200"
    networks:
      - ajudaime-net

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: ajudaime-kibana
    ports:
      - "5601:5601"
    networks:
      - ajudaime-net

networks:
  ajudaime-net:
    external:
      name: ajudaime_network
