version: '3.5'

services:
  elasticsearch:
    image: elasticsearch:6.8.0
    container_name: ajudaime-elasticsearch
#    environment:
#      - cluster.name=docker-cluster
#      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USER}
#      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
#      - xpack.security.audit.enabled=true
#      - node.master=true
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - ajudaime-net

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    container_name: ajudaime-kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
#    environment:
#      - elasticsearch.url=http://elasticsearch:9200
#      - elasticsearch.username=${ELASTICSEARCH_USER}
#      - elasticsearch.password=${ELASTICSEARCH_PASSWORD}
#      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    ports:
      - "5601:5601"
    networks:
      - ajudaime-net

networks:
  ajudaime-net:
    external:
      name: ajudaime_network
